#!/bin/bash
aptitude install install bind9 bind9utils bind9-doc dnsutils

############################################################
vim /etc/bind/named.conf.options

options {
        directory "/var/cache/bind";
        auth-nxdomain no;    # conform to RFC1035
        listen-on port 53 { localhost; 192.168.1.0/24; };
        allow-query { localhost; 192.168.1.0/24; };
        forwarders { 8.8.8.8; };
        recursion yes;
        };

############################################################

echo "zone    "$1"   {" >> named.conf.local
echo "       type master;" >> named.conf.local
echo "       file    "/etc/bind/$1.db";" >> named.conf.local
echo "};" >> named.conf.local
echo "zone   "1.168.192.in-addr.arpa"        {" >> named.conf.local
echo "       type master;" >> named.conf.local
echo "       file    "/etc/bind/rev.$1.db";" >> named.conf.local
echo " };" >> named.conf.local
 
 ############################################################
 
 
 
